# generated by matugen — do not edit
# fish's command-line colours, from the wallpaper (Ether Shell).  New
# terminals pick them up; open ones keep theirs until restarted.

# the starship prompt in the same colours (delete this line to use your
# own ~/.config/starship.toml again)
test -f $HOME/.config/starship/ether.toml; and set -gx STARSHIP_CONFIG $HOME/.config/starship/ether.toml
set -g fish_color_normal         {{colors.on_surface.default.hex_stripped}}
set -g fish_color_command        {{colors.primary.default.hex_stripped}}
set -g fish_color_keyword        {{colors.magenta.default.hex_stripped}}
set -g fish_color_quote          {{colors.green.default.hex_stripped}}
set -g fish_color_redirection    {{colors.cyan.default.hex_stripped}}
set -g fish_color_end            {{colors.tertiary.default.hex_stripped}}
set -g fish_color_error          {{colors.red.default.hex_stripped}}
set -g fish_color_param          {{colors.on_surface.default.hex_stripped}}
set -g fish_color_option         {{colors.secondary.default.hex_stripped}}
set -g fish_color_comment        {{colors.outline.default.hex_stripped}}
set -g fish_color_operator       {{colors.yellow.default.hex_stripped}}
set -g fish_color_escape         {{colors.cyan.default.hex_stripped}}
set -g fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -g fish_color_valid_path     --underline
set -g fish_color_selection      --background={{colors.primary_container.default.hex_stripped}}
set -g fish_color_search_match   --background={{colors.secondary_container.default.hex_stripped}}
set -g fish_color_cancel         {{colors.red.default.hex_stripped}}
set -g fish_pager_color_prefix       {{colors.primary.default.hex_stripped}} --bold
set -g fish_pager_color_completion   {{colors.on_surface.default.hex_stripped}}
set -g fish_pager_color_description  {{colors.on_surface_variant.default.hex_stripped}}
set -g fish_pager_color_progress     {{colors.on_primary.default.hex_stripped}} --background={{colors.primary.default.hex_stripped}}
set -g fish_pager_color_selected_background --background={{colors.primary_container.default.hex_stripped}}
