# generated by matugen — do not edit
# fish's command-line colours, from the wallpaper (Ether Shell), as universal
# variables: fish shares those live between every running session, so open
# terminals recolour the moment the wallpaper changes.  (Sourced once after
# each theme change, not at startup; universal variables persist.)

# the starship prompt in the same colours (delete this line to use your
# own ~/.config/starship.toml again)
test -f $HOME/.config/starship/ether.toml; and set -Ux STARSHIP_CONFIG $HOME/.config/starship/ether.toml
set -U fish_color_normal         {{colors.on_surface.default.hex_stripped}}
set -U fish_color_command        {{colors.vivid_value.default.hex_stripped}}
set -U fish_color_keyword        {{colors.magenta.default.hex_stripped}}
set -U fish_color_quote          {{colors.green.default.hex_stripped}}
set -U fish_color_redirection    {{colors.cyan.default.hex_stripped}}
set -U fish_color_end            {{colors.third_value.default.hex_stripped}}
set -U fish_color_error          {{colors.red.default.hex_stripped}}
set -U fish_color_param          {{colors.on_surface.default.hex_stripped}}
set -U fish_color_option         {{colors.second_value.default.hex_stripped}}
set -U fish_color_comment        {{colors.outline.default.hex_stripped}}
set -U fish_color_operator       {{colors.yellow.default.hex_stripped}}
set -U fish_color_escape         {{colors.cyan.default.hex_stripped}}
set -U fish_color_autosuggestion {{colors.outline.default.hex_stripped}}
set -U fish_color_valid_path     --underline
set -U fish_color_selection      --background={{colors.primary_container.default.hex_stripped}}
set -U fish_color_search_match   --background={{colors.secondary_container.default.hex_stripped}}
set -U fish_color_cancel         {{colors.red.default.hex_stripped}}
set -U fish_pager_color_prefix       {{colors.vivid_value.default.hex_stripped}} --bold
set -U fish_pager_color_completion   {{colors.on_surface.default.hex_stripped}}
set -U fish_pager_color_description  {{colors.on_surface_variant.default.hex_stripped}}
set -U fish_pager_color_progress     {{colors.on_vivid_value.default.hex_stripped}} --background={{colors.vivid_value.default.hex_stripped}}
set -U fish_pager_color_selected_background --background={{colors.primary_container.default.hex_stripped}}
