-- generated by matugen — do not edit
-- Same gradient form the stock config uses, so there is no string-vs-table
-- mismatch when this overrides it.
hl.config({
    general = {
        col = {
            active_border = {
                colors = {
                    "rgba({{colors.vivid_value.default.hex_stripped}}99)",
                    "rgba({{colors.tertiary.default.hex_stripped}}99)",
                },
                angle = 45,
            },
            inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",
        },
    },
})
