
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --



-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- Values the quickshell Settings panel controls.  It writes
-- ~/.config/hypr/shell-settings.lua (a plain `return { ... }` table)
-- and runs `hyprctl reload`, since Hyprland does not watch files that
-- are dofile()d.  Every value falls back to the default here, so a
-- missing or broken file changes nothing.  Change these defaults
-- here; change your own values in the panel.
local S = {}
do
    local ok, t = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/shell-settings.lua")
    if ok and type(t) == "table" then S = t end
end

local function num(v, default, lo, hi)
    if type(v) ~= "number" then return default end
    return math.max(lo, math.min(hi, v))
end
local function int(v, default, lo, hi)
    return math.floor(num(v, default, lo, hi) + 0.5)
end

-- Monitors.  The panel's Displays page writes S.monitors as
--   { ["DP-1"] = { mode = "3840x2160@239.99", position = "0x1440", scale = 1.25 } }
-- and reverts on its own unless the change is confirmed.  Anything
-- missing or malformed falls back to the defaults given here.
local M = type(S.monitors) == "table" and S.monitors or {}

local function monitor(output, def)
    local m = type(M[output]) == "table" and M[output] or {}
    local mode = (type(m.mode) == "string" and m.mode:match("^%d+x%d+@[%d%.]+$"))
                 and m.mode or def.mode
    local pos  = (type(m.position) == "string" and m.position:match("^%-?%d+x%-?%d+$"))
                 and m.position or def.position
    hl.monitor({
        output   = output,
        mode     = mode,
        position = pos,
        scale    = (type(m.scale) == "number" and m.scale >= 0.5 and m.scale <= 3)
                   and m.scale or def.scale,
    })
end

-- Only monitors set up on the Displays page get a rule.  Any other
-- monitor gets Hyprland's own default: its preferred mode, placed
-- automatically.  So a fresh install works on any set of screens.
for output, _ in pairs(M) do
    if type(output) == "string" and output:match("^[%w%-]+$") then
        monitor(output, { mode = "preferred", position = "auto", scale = 1 })
    end
end

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
-- the terminal and file manager come from Settings > Default apps
local function cmd(v, default)
    return (type(v) == "string" and v ~= "") and v or default
end
local terminal    = cmd(S.terminal, "kitty")
local fileManager = cmd(S.file_manager, "dolphin")
-- SUPER + R: rofi, kept as a fallback launcher
local menu        = "sh -c 'pkill rofi || rofi -show drun -theme ~/.config/rofi/launcher.rasi'"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    -- through its start-up script, which keeps it on NVIDIA's driver alone
    -- when that's installed (about 100 MB less)
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/ether-shell")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/restore-wall")
    hl.exec_cmd("hypridle")
    -- clipboard history: text, and images (the clipboard panel shows them
    -- as thumbnails)
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

local gapsIn      = int(S.gaps_in,          4,   0, 40)
local gapsOut     = int(S.gaps_out,         1,   0, 60)
local borderSize  = int(S.border_size,      2,   0, 8)
local rounding    = int(S.rounding,         12,  0, 32)
local winActive   = num(S.active_opacity,   1.0, 0.3, 1)
local winInactive = num(S.inactive_opacity, 1.0, 0.3, 1)
local blurSize    = int(S.blur_size,        4,   1, 16)
local blurPasses  = int(S.blur_passes,      3,   1, 4)
local animOn      = S.animations ~= false
-- game mode (quick settings): blur, shadows and animations off, for the
-- highest frame rate; everything returns when it's switched off
local gameMode    = S.game_mode == true
-- For games (Settings > Windows > Gaming):
--   vrr: variable refresh rate (G-SYNC / FreeSync).  0 off, 1 always,
--        2 fullscreen only (the default), 3 fullscreen games and video only
--   direct_scanout: a fullscreen window's frames go straight to the monitor,
--        skipping compositing: less latency and GPU work.  0 off, 1 any
--        fullscreen window, 2 only windows that say they're games (default)
local vrrMode     = int(S.vrr,            2, 0, 3)
local scanout     = int(S.direct_scanout, 2, 0, 2)
local animSpeed   = num(S.anim_speed,       1.0, 0.25, 4)   -- 2 = twice as fast
local repeatRate  = int(S.repeat_rate,      25,  5,  100)   -- keys per second
local repeatDelay = int(S.repeat_delay,     600, 150, 1500) -- ms before repeating
local pointerSpd  = num(S.sensitivity,      0,   -1, 1)
local accelFlat   = S.accel_flat == true
local naturalScr  = S.natural_scroll == true
local followMouse = S.follow_mouse ~= false                 -- false = focus on click

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in     = gapsIn,
        gaps_out    = gapsOut,
        border_size = borderSize,

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = rounding,
        rounding_power = 2,

        -- transparency of focused and unfocused windows
        active_opacity   = winActive,
        inactive_opacity = winInactive,

        shadow = {
            enabled = not gameMode and (true),
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        -- KWin blurs a rectangle, which is why pills had square corners
        -- there.  Hyprland blurs the layer surface and rounds it to match.
        blur = {
            enabled     = not gameMode,
            size        = blurSize,    -- radius; raise for a heavier frost
            passes      = blurPasses,  -- keep >=3 when size is large, or it banks
            noise       = 0.02,
            contrast    = 1.0,
            brightness  = 1.0,
            vibrancy    = 0.18,
            popups      = true,        -- blur behind menus and tooltips too
            new_optimizations = true,
        },
    },

    animations = {
        enabled = animOn and not gameMode,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("glide",          { type = "bezier", points = { {0.16, 1},    {0.3, 1}     } })

-- Default springs.  A spring's timing comes from its physics, not
-- from an animation's speed, so the panel's speed setting scales the
-- spring itself.  Duration goes with sqrt(mass / stiffness), so
-- stretching time by f means mass * f^2 (or stiffness / f^2), with
-- damping * f keeping the bounce the same shape.
--   slower (f > 1): raise the mass
--   faster (f < 1): raise the stiffness instead, because Hyprland
--                   rejects a spring mass below 0.5
local f = 1 / animSpeed
local springMass, springStiff = 1, 238.1191
if f >= 1 then
    springMass  = springMass * f * f
else
    springStiff = springStiff / (f * f)
end
hl.curve("easy",           { type = "spring", mass = springMass, stiffness = springStiff, dampening = 24.21279333 * f })

-- every animation goes through here so the panel's speed setting
-- scales them all together (Hyprland's speed is a duration: lower
-- is faster)
local function anim(t)
    t.speed = t.speed / animSpeed
    hl.animation(t)
end

anim({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
anim({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
anim({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
anim({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
anim({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
anim({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
anim({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
anim({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
anim({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
anim({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
anim({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
anim({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
anim({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
-- Switching workspaces (Settings > Windows > Switching workspaces).
-- Only the "workspaces" leaf decides it: workspacesIn and workspacesOut
-- used to be set to a quick fade, which overrode the slide and made the
-- switch look almost instant.  They now follow the same style.
--   slide      side to side, like moving along a row (the default)
--   slidevert  up and down
--   glide      a short slide with a fade: subtler
--   fade       a cross-fade
--   off        instant
local wsStyles = {
    slide     = { style = "slide",           speed = 4.5, bezier = "glide" },
    slidevert = { style = "slidevert",       speed = 4.5, bezier = "glide" },
    glide     = { style = "slidefade 20%",   speed = 4,   bezier = "glide" },
    fade      = { style = "fade",            speed = 3,   bezier = "almostLinear" },
}
local wsChoice = wsStyles[S.ws_anim] and S.ws_anim or (S.ws_anim == "off" and "off" or "slide")
local ws = wsStyles[wsChoice]
for _, leaf in ipairs({ "workspaces", "workspacesIn", "workspacesOut" }) do
    if ws then
        anim({ leaf = leaf, enabled = true, speed = ws.speed, bezier = ws.bezier, style = ws.style })
    else
        anim({ leaf = leaf, enabled = false, speed = 1, bezier = "default" })
    end
end
-- the special (scratchpad) workspace always drops in from above
anim({ leaf = "specialWorkspace", enabled = wsChoice ~= "off", speed = 4, bezier = "glide", style = "slidevert" })
anim({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
        vrr                     = vrrMode,
    },
    render = {
        direct_scanout = scanout,
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        repeat_rate  = repeatRate,
        repeat_delay = repeatDelay,

        -- 1: focus follows the mouse.  2: click to focus, while scrolling
        -- still goes to whatever window is under the pointer.
        follow_mouse = followMouse and 1 or 2,

        sensitivity    = pointerSpd, -- -1.0 - 1.0, 0 means no modification.
        accel_profile  = accelFlat and "flat" or nil,  -- nil keeps libinput's default
        natural_scroll = naturalScr,

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

hl.env("QT_QPA_PLATFORMTHEME", "kde")
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- MORE BINDS I GUESS, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more

-- ---- apps -----------------------------------------------------
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal),
        { description = "Terminal" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager),
        { description = "File manager" })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu),
        { description = "App menu" })

-- the shell's own launcher: apps, maths, emoji, clipboard, commands
hl.bind("SUPER_L", hl.dsp.exec_cmd("qs ipc call launcher toggle"),
    { release = true, ignore_mods = true, description = "Launcher (tap SUPER)" })

-- ---- windows --------------------------------------------------
hl.bind(mainMod .. " + Q", hl.dsp.window.close(),
        { description = "Close window" })
hl.bind(mainMod .. " + C", hl.dsp.window.close(),
        { description = "Close window" })
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }),
        { description = "Toggle floating" })
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo(),
        { description = "Toggle pseudotile" })
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"),
        { description = "Toggle split direction" })

hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }),
        { description = "Focus left" })
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }),
        { description = "Focus right" })
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }),
        { description = "Focus up" })
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }),
        { description = "Focus down" })

-- Window keys.  Each one is set up through safeBind: if Hyprland ever
-- rejects its options, that key is skipped (and noted in Hyprland's log)
-- instead of the whole config failing to load.
local function safeBind(keys, make, opts)
    local ok, d = pcall(make)
    if ok and d then
        hl.bind(keys, d, opts)
    else
        hl.print("Ether Shell: skipped the bind " .. keys .. ": " .. tostring(d))
    end
end

-- fullscreen, and maximised (fills the screen but keeps the bar and gaps)
safeBind(mainMod .. " + F", function()
    return hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }) end,
    { description = "Fullscreen" })
safeBind(mainMod .. " + SHIFT + F", function()
    return hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }) end,
    { description = "Maximise" })

-- move the window, and resize it (hold to keep going)
for _, d in ipairs({ { key = "left", x = -40, y = 0 }, { key = "right", x = 40, y = 0 },
                     { key = "up", x = 0, y = -40 },   { key = "down", x = 0, y = 40 } }) do
    safeBind(mainMod .. " + SHIFT + " .. d.key, function()
        return hl.dsp.window.move({ direction = d.key }) end,
        { description = "Move window " .. d.key })
    safeBind(mainMod .. " + CTRL + " .. d.key, function()
        return hl.dsp.window.resize({ x = d.x, y = d.y, relative = true }) end,
        { description = "Resize window " .. d.key, repeating = true })
end

-- back to the last workspace on this monitor
safeBind(mainMod .. " + Tab", function()
    return hl.dsp.focus({ workspace = "previous_per_monitor" }) end,
    { description = "Last workspace" })

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),
        { mouse = true, description = "Drag window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(),
        { mouse = true, description = "Resize window" })

-- ---- shell ----------------------------------------------------
hl.bind("ALT + Tab", hl.dsp.exec_cmd("qs ipc call overview toggle"),
        { description = "Workspace overview" })
-- the clipboard panel, down the right side
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("qs ipc call clipboard toggle"),
        { description = "Clipboard history" })
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("qs ipc call ai toggle"),
        { description = "AI assistant" })
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("qs ipc call cheatsheet toggle"),
        { description = "This cheatsheet" })

-- ---- system ---------------------------------------------------
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/shot"),
        { description = "Screenshot region" })
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/shot full"),
        { description = "Screenshot screen" })
-- the wallpaper selector (the rofi list if the shell isn't running)
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd(
    "qs ipc call wallpaper toggle || " .. os.getenv("HOME") .. "/.local/bin/setwall"),
        { description = "Wallpaper selector" })
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"),
        { description = "Lock screen" })
-- Ether Shell's panels.  (There's no key that quits Hyprland outright: Log out is
-- in the power menu, behind a countdown, so one slip can't end the session.)
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("qs ipc call quick toggle"),
        { description = "Quick settings" })
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd("qs ipc call power toggle"),
        { description = "Power menu" })
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd("qs ipc call settings toggle"),
        { description = "Settings" })
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("qs ipc call launcher emoji"),
        { description = "Emoji picker" })

-- ---- workspaces -----------------------------------------------
-- The keys 1-9 then 0 walk the main workspace list in order (default
-- 1-10).  If the settings name a main and a second monitor, those
-- workspaces are pinned to them; otherwise Hyprland places them.
-- Workspace rules apply at CREATION only: after changing them, move
-- any existing workspace or log out once.
local function intList(v, default)
    if type(v) ~= "table" then return default end
    local out = {}
    for _, x in ipairs(v) do
        if type(x) == "number" and x >= 1 then out[#out + 1] = math.floor(x) end
    end
    return #out > 0 and out or default
end
local main   = intList(S.main_workspaces, { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 })
local second = intList(S.second_workspaces, { 11, 12, 13, 14, 15 })
local mainOut   = cmd(S.main_output, "")
local secondOut = cmd(S.second_output, "")

if mainOut ~= "" then
    for _, id in ipairs(main) do
        hl.workspace_rule({ workspace = tostring(id), monitor = mainOut })
    end
end
if secondOut ~= "" then
    for _, id in ipairs(second) do
        hl.workspace_rule({ workspace = tostring(id), monitor = secondOut })
    end
end

-- SUPER + number goes to the focused monitor's own workspaces: the shell
-- knows which monitor has focus, and Hyprland's binds can't ask.  If the
-- shell isn't running, the keys fall back to the main monitor's.
for i, id in ipairs(main) do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.exec_cmd(
        "qs ipc call ws go " .. i .. " || hyprctl dispatch 'hl.dsp.focus({ workspace = " .. id .. " })'"),
        { description = "Workspace " .. i })
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.exec_cmd(
        "qs ipc call ws send " .. i .. " || hyprctl dispatch 'hl.dsp.window.move({ workspace = " .. id .. " })'"),
        { description = "Send to workspace " .. i })
end

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }),
        { description = "Next workspace" })
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }),
        { description = "Previous workspace" })

-- ---- media / hardware keys ------------------------------------
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
        { locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
        { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
        { locked = true, description = "Mute output" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
        { locked = true, description = "Mute microphone" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),
        { locked = true, repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),
        { locked = true, repeating = true, description = "Brightness down" })

hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),
        { locked = true, description = "Next track" })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),
        { locked = true, description = "Previous track" })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"),
        { locked = true, description = "Play / pause" })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"),
        { locked = true, description = "Play / pause" })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})


----------------------------------------------------------------
--  Layer blur
----------------------------------------------------------------

-- Layer surfaces need blur asked for by namespace.  Quickshell's surfaces
-- all use the "quickshell" namespace; rofi uses "rofi".
hl.layer_rule({
    name    = "blur-quickshell",
    match   = { namespace = "^quickshell$" },
    blur    = true,
    ignore_alpha = 0.2,   -- don't blur fully transparent regions
})

hl.layer_rule({
    name    = "blur-rofi",
    match   = { namespace = "^rofi$" },
    blur    = true,
    ignore_alpha = 0.2,
})

-- any key or mouse movement brings the screens back after DPMS off
hl.config({
    misc = {
        mouse_move_enables_dpms = true,
        key_press_enables_dpms  = true,
    },
})

-- Xwayland Scaling
hl.config({
  xwayland = {
    force_zero_scaling = true,
  },
})

hl.config({
    cursor = {
        no_warps = true,
    },
})

-- MUST stay last: whatever sets general.col last wins.  pcall so a
-- missing colors.lua (before the first setwall) can't break the config.
pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
